In [1]:
import numpy as np
import pandas as pd

In [24]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105],
    "name": ["Rahul", "Amit", "Priya", "Neha", "Rohit"],
    "city": ["Bhopal", "Delhi", "Mumbai", "Bhopal", "Indore"]
})

marks = pd.DataFrame({
    "student_id": [101, 102, 103, 106, 107],
    "subject": ["Python", "Python", "Python", "Python", "Python"],
    "marks": [85, 92, 78, 88, 75]
})

In [25]:
students

   student_id   name    city
0         101  Rahul  Bhopal
1         102   Amit   Delhi
2         103  Priya  Mumbai
3         104   Neha  Bhopal
4         105  Rohit  Indore

In [35]:
marks

   student_id subject  marks
0         101  Python     85
1         102  Python     92
2         103  Python     78
3         106  Python     88
4         107  Python     75

In [ ]:
# Merging two tables

In [27]:
pd.merge(students,marks, on="student_id",how="inner")

   student_id   name    city subject  marks
0         101  Rahul  Bhopal  Python     85
1         102   Amit   Delhi  Python     92
2         103  Priya  Mumbai  Python     78

In [28]:
pd.merge(students,marks, on="student_id",how="left")

   student_id   name    city subject  marks
0         101  Rahul  Bhopal  Python   85.0
1         102   Amit   Delhi  Python   92.0
2         103  Priya  Mumbai  Python   78.0
3         104   Neha  Bhopal     NaN    NaN
4         105  Rohit  Indore     NaN    NaN

In [29]:
pd.merge(students,marks, on="student_id",how="right")

   student_id   name    city subject  marks
0         101  Rahul  Bhopal  Python     85
1         102   Amit   Delhi  Python     92
2         103  Priya  Mumbai  Python     78
3         106    NaN     NaN  Python     88
4         107    NaN     NaN  Python     75

In [34]:
pd.merge(students,marks, on="student_id",how="outer")

   student_id   name    city subject  marks
0         101  Rahul  Bhopal  Python   85.0
1         102   Amit   Delhi  Python   92.0
2         103  Priya  Mumbai  Python   78.0
3         104   Neha  Bhopal     NaN    NaN
4         105  Rohit  Indore     NaN    NaN
5         106    NaN     NaN  Python   88.0
6         107    NaN     NaN  Python   75.0

In [36]:
# Concatination of two tables

In [37]:
pd.concat([students,marks])

   student_id   name    city subject  marks
0         101  Rahul  Bhopal     NaN    NaN
1         102   Amit   Delhi     NaN    NaN
2         103  Priya  Mumbai     NaN    NaN
3         104   Neha  Bhopal     NaN    NaN
4         105  Rohit  Indore     NaN    NaN
0         101    NaN     NaN  Python   85.0
1         102    NaN     NaN  Python   92.0
2         103    NaN     NaN  Python   78.0
3         106    NaN     NaN  Python   88.0
4         107    NaN     NaN  Python   75.0

In [38]:
pd.concat([students,marks], ignore_index=True)

   student_id   name    city subject  marks
0         101  Rahul  Bhopal     NaN    NaN
1         102   Amit   Delhi     NaN    NaN
2         103  Priya  Mumbai     NaN    NaN
3         104   Neha  Bhopal     NaN    NaN
4         105  Rohit  Indore     NaN    NaN
5         101    NaN     NaN  Python   85.0
6         102    NaN     NaN  Python   92.0
7         103    NaN     NaN  Python   78.0
8         106    NaN     NaN  Python   88.0
9         107    NaN     NaN  Python   75.0

In [41]:
pd.concat([students,marks], axis=1) # concating horizontally

   student_id   name    city  student_id subject  marks
0         101  Rahul  Bhopal         101  Python     85
1         102   Amit   Delhi         102  Python     92
2         103  Priya  Mumbai         103  Python     78
3         104   Neha  Bhopal         106  Python     88
4         105  Rohit  Indore         107  Python     75