In [5]:
import pandas as pd
import numpy as np

In [6]:
data = {
    "name": ["Utsav", "Rahul", "Priya", "Aman", "Sneha", "Rohit", "Neha", "Vikash"],
    "age": [22, 24, np.nan, 25, 23, np.nan, 22, 24],
    "gender": ["Male", "Male", "Female", "Male", np.nan, "Male", "Female", "Male"],
    "city": ["Bhopal", "Delhi", "Mumbai", np.nan, "Indore", "Pune", "Jaipur", "Bangalore"],
    "salary": [45000, np.nan, 40000, 65000, np.nan, 70000, 52000, 60000]
}

df = pd.DataFrame(data)
df

     name   age  gender       city   salary
0   Utsav  22.0    Male     Bhopal  45000.0
1   Rahul  24.0    Male      Delhi      NaN
2   Priya   NaN  Female     Mumbai  40000.0
3    Aman  25.0    Male        NaN  65000.0
4   Sneha  23.0     NaN     Indore      NaN
5   Rohit   NaN    Male       Pune  70000.0
6    Neha  22.0  Female     Jaipur  52000.0
7  Vikash  24.0    Male  Bangalore  60000.0

In [7]:
df.isna()

    name    age  gender   city  salary
0  False  False   False  False   False
1  False  False   False  False    True
2  False   True   False  False   False
3  False  False   False   True   False
4  False  False    True  False    True
5  False   True   False  False   False
6  False  False   False  False   False
7  False  False   False  False   False

In [8]:
df.isna().sum()

name      0
age       2
gender    1
city      1
salary    2
dtype: int64

In [9]:
df.isna().sum().sum()

np.int64(6)

In [10]:
df.dropna()

     name   age  gender       city   salary
0   Utsav  22.0    Male     Bhopal  45000.0
6    Neha  22.0  Female     Jaipur  52000.0
7  Vikash  24.0    Male  Bangalore  60000.0

In [11]:
df

     name   age  gender       city   salary
0   Utsav  22.0    Male     Bhopal  45000.0
1   Rahul  24.0    Male      Delhi      NaN
2   Priya   NaN  Female     Mumbai  40000.0
3    Aman  25.0    Male        NaN  65000.0
4   Sneha  23.0     NaN     Indore      NaN
5   Rohit   NaN    Male       Pune  70000.0
6    Neha  22.0  Female     Jaipur  52000.0
7  Vikash  24.0    Male  Bangalore  60000.0

In [12]:
df.dropna(axis=1)

     name
0   Utsav
1   Rahul
2   Priya
3    Aman
4   Sneha
5   Rohit
6    Neha
7  Vikash

In [13]:
df

     name   age  gender       city   salary
0   Utsav  22.0    Male     Bhopal  45000.0
1   Rahul  24.0    Male      Delhi      NaN
2   Priya   NaN  Female     Mumbai  40000.0
3    Aman  25.0    Male        NaN  65000.0
4   Sneha  23.0     NaN     Indore      NaN
5   Rohit   NaN    Male       Pune  70000.0
6    Neha  22.0  Female     Jaipur  52000.0
7  Vikash  24.0    Male  Bangalore  60000.0

In [14]:
df.fill(0)

AttributeError: 'DataFrame' object has no attribute 'fill'

In [15]:
df.fillna(0)

     name   age  gender       city   salary
0   Utsav  22.0    Male     Bhopal  45000.0
1   Rahul  24.0    Male      Delhi      0.0
2   Priya   0.0  Female     Mumbai  40000.0
3    Aman  25.0    Male          0  65000.0
4   Sneha  23.0       0     Indore      0.0
5   Rohit   0.0    Male       Pune  70000.0
6    Neha  22.0  Female     Jaipur  52000.0
7  Vikash  24.0    Male  Bangalore  60000.0

In [17]:
df["salary"]=df["salary"].fillna(df["salary"].mean())
df

     name   age  gender       city        salary
0   Utsav  22.0    Male     Bhopal  45000.000000
1   Rahul  24.0    Male      Delhi  55333.333333
2   Priya   NaN  Female     Mumbai  40000.000000
3    Aman  25.0    Male        NaN  65000.000000
4   Sneha  23.0     NaN     Indore  55333.333333
5   Rohit   NaN    Male       Pune  70000.000000
6    Neha  22.0  Female     Jaipur  52000.000000
7  Vikash  24.0    Male  Bangalore  60000.000000

In [21]:
df["age"]=df["age"].fillna(df["age"].mean())
df

     name        age  gender       city        salary
0   Utsav  22.000000    Male     Bhopal  45000.000000
1   Rahul  24.000000    Male      Delhi  55333.333333
2   Priya  23.333333  Female     Mumbai  40000.000000
3    Aman  25.000000    Male        NaN  65000.000000
4   Sneha  23.000000     NaN     Indore  55333.333333
5   Rohit  23.333333    Male       Pune  70000.000000
6    Neha  22.000000  Female     Jaipur  52000.000000
7  Vikash  24.000000    Male  Bangalore  60000.000000