In [1]:
import numpy as np
import pandas as pd

In [26]:
data = {
    "name": ["Utsav", "Rahul", "Priya", "Aman", "Sneha", "Rohit", "Neha", "Vikash"],
    "age": [22, 24, 21, 25, 23, 26, 22, 24],
    "city": ["Bhopal", "Delhi", "Mumbai", "Patna", "Indore", "Patna", "Jaipur", "Bangalore"],
    "salary": [45000, 55000, 40000, 65000, 48000, 70000, 52000, 60000]
}
pd.Series(data)

name      [Utsav, Rahul, Priya, Aman, Sneha, Rohit, Neha...
age                        [22, 24, 21, 25, 23, 26, 22, 24]
city      [Bhopal, Delhi, Mumbai, Patna, Indore, Patna, ...
salary    [45000, 55000, 40000, 65000, 48000, 70000, 520...
dtype: object

In [27]:
df=pd.DataFrame(data)
df

     name  age       city  salary
0   Utsav   22     Bhopal   45000
1   Rahul   24      Delhi   55000
2   Priya   21     Mumbai   40000
3    Aman   25      Patna   65000
4   Sneha   23     Indore   48000
5   Rohit   26      Patna   70000
6    Neha   22     Jaipur   52000
7  Vikash   24  Bangalore   60000

In [28]:
#Selecting col.
df["name"]

0     Utsav
1     Rahul
2     Priya
3      Aman
4     Sneha
5     Rohit
6      Neha
7    Vikash
Name: name, dtype: str

In [29]:
#selecting multiple col.
df[["name","city"]]

     name       city
0   Utsav     Bhopal
1   Rahul      Delhi
2   Priya     Mumbai
3    Aman      Patna
4   Sneha     Indore
5   Rohit      Patna
6    Neha     Jaipur
7  Vikash  Bangalore

In [30]:
#Adding another coll.
df["Gender"]=["Male", "Male", "Female", "Male", "Female", "Male", "Female", "Male"]

In [31]:
df

     name  age       city  salary  Gender
0   Utsav   22     Bhopal   45000    Male
1   Rahul   24      Delhi   55000    Male
2   Priya   21     Mumbai   40000  Female
3    Aman   25      Patna   65000    Male
4   Sneha   23     Indore   48000  Female
5   Rohit   26      Patna   70000    Male
6    Neha   22     Jaipur   52000  Female
7  Vikash   24  Bangalore   60000    Male

In [32]:
#Deleting col.
df.drop("Gender",axis=1,inplace=True)
df

     name  age       city  salary
0   Utsav   22     Bhopal   45000
1   Rahul   24      Delhi   55000
2   Priya   21     Mumbai   40000
3    Aman   25      Patna   65000
4   Sneha   23     Indore   48000
5   Rohit   26      Patna   70000
6    Neha   22     Jaipur   52000
7  Vikash   24  Bangalore   60000

In [33]:
df

     name  age       city  salary
0   Utsav   22     Bhopal   45000
1   Rahul   24      Delhi   55000
2   Priya   21     Mumbai   40000
3    Aman   25      Patna   65000
4   Sneha   23     Indore   48000
5   Rohit   26      Patna   70000
6    Neha   22     Jaipur   52000
7  Vikash   24  Bangalore   60000

In [34]:
#Selecting the row
df.loc[0]

name       Utsav
age           22
city      Bhopal
salary     45000
Name: 0, dtype: object

In [35]:
#Selecting multiple rows 
df.loc[[2,3]]

    name  age    city  salary
2  Priya   21  Mumbai   40000
3   Aman   25   Patna   65000

In [36]:
df.loc[[5,6]][["name","age","city"]]

    name  age    city
5  Rohit   26   Patna
6   Neha   22  Jaipur

In [37]:
#Conditional statement
#People with age above 23
df[df["age"] >= 23]

     name  age       city  salary
1   Rahul   24      Delhi   55000
3    Aman   25      Patna   65000
4   Sneha   23     Indore   48000
5   Rohit   26      Patna   70000
7  Vikash   24  Bangalore   60000

In [40]:
#Age must be above 23 and city must me "Patna"
df[(df["age"]>23) & (df["city"]=="Patna")]

    name  age   city  salary
3   Aman   25  Patna   65000
5  Rohit   26  Patna   70000